server:
  port: 8083
  
  
#springdoc:
#   swagger-ui:
#    disable-swagger-default-url: false
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studentdb
      password: password
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver               
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect      
 
  application:
      name: STUDENT-SERVICE